### ISSUE TITLE
comments from Mark

### ISSUE THREAD

**Issue by forero** [astroandes/LAEsBayes#2]
- Can we interpret f_occ as a `duty cycle'? Meaning that halos of mass M are only`on' as Lya emitters for a fraction of the time. This fraction is not exactly given by f_occ, but should be related to this?
- I could not really see how you assign Lya luminosities to halos?
- Do you fold in constrains from the luminosity function? If so, how steep is your faint end of the LAE luminosty function? Some indications that this LF is quite steep (e.g. Konno et al. 2016 - from Ouchi group; also gronke et al. 2015). For steep LFs, I can see why the ACF is most sensitive to M-min, as the halos with M_max if Lya luminosity scales with halo mass: the total clustering signature is probably dominated my the least luminous LAEs, which are likely hosted by the least massive halos. 
- Typos: on the bottom of page 2 Delta M = log M_max - log M_max, second one should be log  M_min.

**Comment by forero** [comment]
@jemejia algunos comentarios de Mark, para que me ayudes a clarificarlos en el texto. Ya recibiste tu comentarios externos?

**Comment by jemejia** [comment]
@forero Disculpa la tardanza en responder. Déjame revisar este asunto entre hoy y mañana. Rápidamente parecen fáciles de corregir. Aún no he recibido comentarios las personas externas.
